// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaaydhfciidrbawkyzgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhYXlkaGZjaWlkcmJhd2t5emd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNDMwNzIsImV4cCI6MjA4ODkxOTA3Mn0.czjSaV2TlZPudWAZ2bgFJGJQZaZWi2N7F-z-nusU45E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});