// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcgktmkrcdymvuflobfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZ2t0bWtyY2R5bXZ1ZmxvYmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MDQ0MTgsImV4cCI6MjA4ODk4MDQxOH0.g9RpDUobr7RqIIs1SRAnZmqDlYrrVEduThwMe94wrnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});